{% set name = "apache-airflow-providers-tabular" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_tabular-{{ version }}.tar.gz
  sha256: 0b66a1f2f0d9e07f7404adf55d77ffb99e14d810f39e677f9d6c4c1c17dc76d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - apache-airflow-providers-apache-iceberg
    - python >=3.8
    - apache-airflow >=2.8.0

test:
  imports:
    - airflow.providers.tabular
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-tabular for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/tabular/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-tabular/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
